#!/bin/bash
### Changes the place of ± and ` on the keyboard.

if hidutil property --get "UserKeyMapping" | grep -q '30064771172'; then
   hidutil property --set '{"UserKeyMapping":[]}'
else
    hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000035,"HIDKeyboardModifierMappingDst":0x700000064},{"HIDKeyboardModifierMappingSrc":0x700000064,"HIDKeyboardModifierMappingDst":0x700000035}]}'
fi
